Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 1 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P5: HAS (BIRD, B-WING)
Iteration (RT) = 767


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P7: HAS (BIRD, B-FOOT)
Iteration (RT) = 767

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P5: HAS (BIRD, B-WING)
Iteration (RT) = 1304


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P7: HAS (BIRD, B-FOOT)
Iteration (RT) = 1304


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P3: CAN (BIRD, FLY)
Iteration (RT) = 1325


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P10: ISA (BIRD, ANIMAL)
Iteration (RT) = 1325


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P11: ISA (CANARY, BIRD)
Iteration (RT) = 1327


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P12: ISA (PARROT, BIRD)
Iteration (RT) = 1327



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    BIRDS = 0.879
  Props:
    From P1 to:    P5 = 0.441    P7 = 0.441
  SPs:
    From SP1.1 to:    SP5.1 = 0.766    SP7.1 = 0.766
    From SP1.2 to:    SP5.2 = 0.555    SP7.2 = 0.555
  Preds:
    From HAS1 to:    HAS1 = 0.978
    From HAS2 to:    HAS2 = 0.972
  Objs:
    From BIRD to:    BIRD = 0.978
    From ENZYME to:    B-WING = 0.132    B-FOOT = 0.132

From WorkSpace to ToVerify:
  Groups:
    From BIRDS to:    TOVERIFY = 0.879
  Props:
    From P5 to:    P1 = 0.441
    From P7 to:    P1 = 0.441
  SPs:
    From SP5.1 to:    SP1.1 = 0.766
    From SP5.2 to:    SP1.2 = 0.555
    From SP7.1 to:    SP1.1 = 0.766
    From SP7.2 to:    SP1.2 = 0.555
  Preds:
    From HAS1 to:    HAS1 = 0.978
    From HAS2 to:    HAS2 = 0.972
  Objs:
    From BIRD to:    BIRD = 0.978
    From B-WING to:    ENZYME = 0.132
    From B-FOOT to:    ENZYME = 0.132

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 2 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P5: HAS (BIRD, B-WING)
Iteration (RT) = 763


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P7: HAS (BIRD, B-FOOT)
Iteration (RT) = 763

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P5: HAS (BIRD, B-WING)
Iteration (RT) = 1304


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P7: HAS (BIRD, B-FOOT)
Iteration (RT) = 1304


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P3: CAN (BIRD, FLY)
Iteration (RT) = 1325


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P10: ISA (BIRD, ANIMAL)
Iteration (RT) = 1326


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P11: ISA (CANARY, BIRD)
Iteration (RT) = 1327


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P12: ISA (PARROT, BIRD)
Iteration (RT) = 1327



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    BIRDS = 0.879
  Props:
    From P1 to:    P5 = 0.441    P7 = 0.441
  SPs:
    From SP1.1 to:    SP5.1 = 0.766    SP7.1 = 0.766
    From SP1.2 to:    SP5.2 = 0.555    SP7.2 = 0.555
  Preds:
    From HAS1 to:    HAS1 = 0.978
    From HAS2 to:    HAS2 = 0.972
  Objs:
    From BIRD to:    BIRD = 0.978
    From ENZYME to:    B-WING = 0.132    B-FOOT = 0.132

From WorkSpace to ToVerify:
  Groups:
    From BIRDS to:    TOVERIFY = 0.879
  Props:
    From P5 to:    P1 = 0.441
    From P7 to:    P1 = 0.441
  SPs:
    From SP5.1 to:    SP1.1 = 0.766
    From SP5.2 to:    SP1.2 = 0.555
    From SP7.1 to:    SP1.1 = 0.766
    From SP7.2 to:    SP1.2 = 0.555
  Preds:
    From HAS1 to:    HAS1 = 0.978
    From HAS2 to:    HAS2 = 0.972
  Objs:
    From BIRD to:    BIRD = 0.978
    From B-WING to:    ENZYME = 0.132
    From B-FOOT to:    ENZYME = 0.132

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 3 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =485


Contradiction detected underMAMMAL.  Active members are: RODENT, ELEPHANT
Simulation iteration (i.e., total RT) =493


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ANIMAL, ENZYME)
Iteration (RT) = 637

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1141


Contradiction detected underMAMMAL.  Active members are: RODENT, ELEPHANT
Simulation iteration (i.e., total RT) =1142


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ANIMAL, ENZYME)
Iteration (RT) = 1168



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALENZYME = 0.879
  Props:
    From P1 to:    P0 = 0.990
  SPs:
    From SP1.1 to:    SP0.1 = 0.993
    From SP1.2 to:    SP0.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    ENZYME = 0.970

From WorkSpace to ToVerify:
  Groups:
    From ANIMALENZYME to:    TOVERIFY = 0.879
  Props:
    From P0 to:    P1 = 0.990
  SPs:
    From SP0.1 to:    SP1.1 = 0.993
    From SP0.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From ENZYME to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 4 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =485


Contradiction detected underMAMMAL.  Active members are: RODENT, ELEPHANT
Simulation iteration (i.e., total RT) =493


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ANIMAL, ENZYME)
Iteration (RT) = 637

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1141


Contradiction detected underMAMMAL.  Active members are: RODENT, ELEPHANT
Simulation iteration (i.e., total RT) =1142


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ANIMAL, ENZYME)
Iteration (RT) = 1168



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALENZYME = 0.879
  Props:
    From P1 to:    P0 = 0.990
  SPs:
    From SP1.1 to:    SP0.1 = 0.993
    From SP1.2 to:    SP0.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    ENZYME = 0.970

From WorkSpace to ToVerify:
  Groups:
    From ANIMALENZYME to:    TOVERIFY = 0.879
  Props:
    From P0 to:    P1 = 0.990
  SPs:
    From SP0.1 to:    SP1.1 = 0.993
    From SP0.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From ENZYME to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 5 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 671

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1147


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 1177



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALS = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From ANIMALS to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 6 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 663

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1142


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 1172



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALS = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From ANIMALS to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 7 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P5: HAS (BIRD, B-WING)
Iteration (RT) = 769


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P7: HAS (BIRD, B-FOOT)
Iteration (RT) = 769

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P5: HAS (BIRD, B-WING)
Iteration (RT) = 1307


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P7: HAS (BIRD, B-FOOT)
Iteration (RT) = 1307


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P3: CAN (BIRD, FLY)
Iteration (RT) = 1328


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P10: ISA (BIRD, ANIMAL)
Iteration (RT) = 1328


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P11: ISA (CANARY, BIRD)
Iteration (RT) = 1330


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P12: ISA (PARROT, BIRD)
Iteration (RT) = 1330



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    BIRDS = 0.879
  Props:
    From P1 to:    P5 = 0.441    P7 = 0.441
  SPs:
    From SP1.1 to:    SP5.1 = 0.766    SP7.1 = 0.766
    From SP1.2 to:    SP5.2 = 0.555    SP7.2 = 0.555
  Preds:
    From HAS1 to:    HAS1 = 0.978
    From HAS2 to:    HAS2 = 0.972
  Objs:
    From BIRD to:    BIRD = 0.978
    From ENZYME to:    B-WING = 0.132    B-FOOT = 0.132

From WorkSpace to ToVerify:
  Groups:
    From BIRDS to:    TOVERIFY = 0.879
  Props:
    From P5 to:    P1 = 0.441
    From P7 to:    P1 = 0.441
  SPs:
    From SP5.1 to:    SP1.1 = 0.766
    From SP5.2 to:    SP1.2 = 0.555
    From SP7.1 to:    SP1.1 = 0.766
    From SP7.2 to:    SP1.2 = 0.555
  Preds:
    From HAS1 to:    HAS1 = 0.978
    From HAS2 to:    HAS2 = 0.972
  Objs:
    From BIRD to:    BIRD = 0.978
    From B-WING to:    ENZYME = 0.132
    From B-FOOT to:    ENZYME = 0.132

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 8 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P4: HAS (CAR, WHEEL)
Iteration (RT) = 641


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P6: CAN (CAR, DRIVE)
Iteration (RT) = 670

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P4: HAS (CAR, WHEEL)
Iteration (RT) = 1173


Contradiction detected underTHING.  Active members are: LIVING, NON-LIVING
Simulation iteration (i.e., total RT) =1252



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    CARS = 0.879
  Props:
    From P1 to:    P4 = 0.990
  SPs:
    From SP1.1 to:    SP4.1 = 0.993
    From SP1.2 to:    SP4.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    CAR = 0.970
    From ENZYME to:    WHEEL = 0.970

From WorkSpace to ToVerify:
  Groups:
    From CARS to:    TOVERIFY = 0.879
  Props:
    From P4 to:    P1 = 0.990
    From P6 to:
  SPs:
    From SP4.1 to:    SP1.1 = 0.993
    From SP4.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From CAR to:    BIRD = 0.970
    From WHEEL to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 9 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =593


Contradiction detected underMAMMAL.  Active members are: RODENT, ELEPHANT
Simulation iteration (i.e., total RT) =601


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ANIMAL, ENZYME)
Iteration (RT) = 632

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ANIMAL, ENZYME)
Iteration (RT) = 1172


Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1256


Contradiction detected underMAMMAL.  Active members are: RODENT, ELEPHANT
Simulation iteration (i.e., total RT) =1257



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALENZYME = 0.879
  Props:
    From P1 to:    P0 = 0.990
  SPs:
    From SP1.1 to:    SP0.1 = 0.993
    From SP1.2 to:    SP0.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    ENZYME = 0.970

From WorkSpace to ToVerify:
  Groups:
    From ANIMALENZYME to:    TOVERIFY = 0.879
  Props:
    From P0 to:    P1 = 0.990
  SPs:
    From SP0.1 to:    SP1.1 = 0.993
    From SP0.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From ENZYME to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 10 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 660

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 1168


Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1249



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALS = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From ANIMALS to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 1 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P4: HAS (CAR, WHEEL)
Iteration (RT) = 642


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P6: CAN (CAR, DRIVE)
Iteration (RT) = 676

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underTHING.  Active members are: LIVING, NON-LIVING
Simulation iteration (i.e., total RT) =1144


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P4: HAS (CAR, WHEEL)
Iteration (RT) = 1176



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    CARS = 0.879
  Props:
    From P1 to:    P4 = 0.990
  SPs:
    From SP1.1 to:    SP4.1 = 0.993
    From SP1.2 to:    SP4.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    CAR = 0.970
    From ENZYME to:    WHEEL = 0.970

From WorkSpace to ToVerify:
  Groups:
    From CARS to:    TOVERIFY = 0.879
  Props:
    From P4 to:    P1 = 0.990
    From P6 to:
  SPs:
    From SP4.1 to:    SP1.1 = 0.993
    From SP4.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From CAR to:    BIRD = 0.970
    From WHEEL to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 2 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P5: HAS (BIRD, B-WING)
Iteration (RT) = 771


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P7: HAS (BIRD, B-FOOT)
Iteration (RT) = 771

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P5: HAS (BIRD, B-WING)
Iteration (RT) = 1305


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P7: HAS (BIRD, B-FOOT)
Iteration (RT) = 1305


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P3: CAN (BIRD, FLY)
Iteration (RT) = 1326


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P10: ISA (BIRD, ANIMAL)
Iteration (RT) = 1326


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P11: ISA (CANARY, BIRD)
Iteration (RT) = 1328


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P12: ISA (PARROT, BIRD)
Iteration (RT) = 1328



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    BIRDS = 0.879
  Props:
    From P1 to:    P5 = 0.441    P7 = 0.441
  SPs:
    From SP1.1 to:    SP5.1 = 0.766    SP7.1 = 0.766
    From SP1.2 to:    SP5.2 = 0.555    SP7.2 = 0.555
  Preds:
    From HAS1 to:    HAS1 = 0.978
    From HAS2 to:    HAS2 = 0.972
  Objs:
    From BIRD to:    BIRD = 0.978
    From ENZYME to:    B-WING = 0.132    B-FOOT = 0.132

From WorkSpace to ToVerify:
  Groups:
    From BIRDS to:    TOVERIFY = 0.879
  Props:
    From P5 to:    P1 = 0.441
    From P7 to:    P1 = 0.441
  SPs:
    From SP5.1 to:    SP1.1 = 0.766
    From SP5.2 to:    SP1.2 = 0.555
    From SP7.1 to:    SP1.1 = 0.766
    From SP7.2 to:    SP1.2 = 0.555
  Preds:
    From HAS1 to:    HAS1 = 0.978
    From HAS2 to:    HAS2 = 0.972
  Objs:
    From BIRD to:    BIRD = 0.978
    From B-WING to:    ENZYME = 0.132
    From B-FOOT to:    ENZYME = 0.132

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 3 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P5: HAS (BIRD, B-WING)
Iteration (RT) = 763


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P7: HAS (BIRD, B-FOOT)
Iteration (RT) = 763

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P5: HAS (BIRD, B-WING)
Iteration (RT) = 1302


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P7: HAS (BIRD, B-FOOT)
Iteration (RT) = 1302


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P3: CAN (BIRD, FLY)
Iteration (RT) = 1323


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P10: ISA (BIRD, ANIMAL)
Iteration (RT) = 1324


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P11: ISA (CANARY, BIRD)
Iteration (RT) = 1325


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P12: ISA (PARROT, BIRD)
Iteration (RT) = 1325



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    BIRDS = 0.879
  Props:
    From P1 to:    P5 = 0.441    P7 = 0.441
  SPs:
    From SP1.1 to:    SP5.1 = 0.766    SP7.1 = 0.766
    From SP1.2 to:    SP5.2 = 0.555    SP7.2 = 0.555
  Preds:
    From HAS1 to:    HAS1 = 0.978
    From HAS2 to:    HAS2 = 0.972
  Objs:
    From BIRD to:    BIRD = 0.978
    From ENZYME to:    B-WING = 0.132    B-FOOT = 0.132

From WorkSpace to ToVerify:
  Groups:
    From BIRDS to:    TOVERIFY = 0.879
  Props:
    From P5 to:    P1 = 0.441
    From P7 to:    P1 = 0.441
  SPs:
    From SP5.1 to:    SP1.1 = 0.766
    From SP5.2 to:    SP1.2 = 0.555
    From SP7.1 to:    SP1.1 = 0.766
    From SP7.2 to:    SP1.2 = 0.555
  Preds:
    From HAS1 to:    HAS1 = 0.978
    From HAS2 to:    HAS2 = 0.972
  Objs:
    From BIRD to:    BIRD = 0.978
    From B-WING to:    ENZYME = 0.132
    From B-FOOT to:    ENZYME = 0.132

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 4 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 666

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 1173


Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1254



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALS = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From ANIMALS to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 5 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 656

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1139


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 1169



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALS = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From ANIMALS to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 6 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P5: HAS (BIRD, B-WING)
Iteration (RT) = 774


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P7: HAS (BIRD, B-FOOT)
Iteration (RT) = 774

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P5: HAS (BIRD, B-WING)
Iteration (RT) = 1313


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P7: HAS (BIRD, B-FOOT)
Iteration (RT) = 1313


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P3: CAN (BIRD, FLY)
Iteration (RT) = 1334


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P10: ISA (BIRD, ANIMAL)
Iteration (RT) = 1335


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P11: ISA (CANARY, BIRD)
Iteration (RT) = 1336


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P12: ISA (PARROT, BIRD)
Iteration (RT) = 1336



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    BIRDS = 0.879
  Props:
    From P1 to:    P5 = 0.441    P7 = 0.441
  SPs:
    From SP1.1 to:    SP5.1 = 0.766    SP7.1 = 0.766
    From SP1.2 to:    SP5.2 = 0.555    SP7.2 = 0.555
  Preds:
    From HAS1 to:    HAS1 = 0.978
    From HAS2 to:    HAS2 = 0.972
  Objs:
    From BIRD to:    BIRD = 0.978
    From ENZYME to:    B-WING = 0.132    B-FOOT = 0.132

From WorkSpace to ToVerify:
  Groups:
    From BIRDS to:    TOVERIFY = 0.879
  Props:
    From P5 to:    P1 = 0.441
    From P7 to:    P1 = 0.441
  SPs:
    From SP5.1 to:    SP1.1 = 0.766
    From SP5.2 to:    SP1.2 = 0.555
    From SP7.1 to:    SP1.1 = 0.766
    From SP7.2 to:    SP1.2 = 0.555
  Preds:
    From HAS1 to:    HAS1 = 0.978
    From HAS2 to:    HAS2 = 0.972
  Objs:
    From BIRD to:    BIRD = 0.978
    From B-WING to:    ENZYME = 0.132
    From B-FOOT to:    ENZYME = 0.132

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 7 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =485


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 636

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1141


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 1167



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALENZYME = 0.879
  Props:
    From P1 to:    P0 = 0.990
  SPs:
    From SP1.1 to:    SP0.1 = 0.993
    From SP1.2 to:    SP0.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ELEPHANT = 0.970
    From ENZYME to:    ENZYME = 0.970

From WorkSpace to ToVerify:
  Groups:
    From ANIMALENZYME to:    TOVERIFY = 0.879
  Props:
    From P0 to:    P1 = 0.990
  SPs:
    From SP0.1 to:    SP1.1 = 0.993
    From SP0.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ELEPHANT to:    BIRD = 0.970
    From ENZYME to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 8 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 654

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1141


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 1171



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALS = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From ANIMALS to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 9 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =620


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 657

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1162


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 1188



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALENZYME = 0.879
  Props:
    From P1 to:    P0 = 0.990
  SPs:
    From SP1.1 to:    SP0.1 = 0.993
    From SP1.2 to:    SP0.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ELEPHANT = 0.970
    From ENZYME to:    ENZYME = 0.970

From WorkSpace to ToVerify:
  Groups:
    From ANIMALENZYME to:    TOVERIFY = 0.879
  Props:
    From P0 to:    P1 = 0.990
  SPs:
    From SP0.1 to:    SP1.1 = 0.993
    From SP0.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ELEPHANT to:    BIRD = 0.970
    From ENZYME to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 10 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 667

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 1175


Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1256



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALS = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From ANIMALS to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

