Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 1 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =706



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 2 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underTHING.  Active members are: LIVING, NON-LIVING
Simulation iteration (i.e., total RT) =829



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:
  Props:
  SPs:
  Preds:
  Objs:

From WorkSpace to ToVerify:
  Groups:
    From CARS to:
  Props:
  SPs:
  Preds:
  Objs:

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 3 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =707



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 4 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =820



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 5 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)


* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 6 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underTHING.  Active members are: LIVING, NON-LIVING
Simulation iteration (i.e., total RT) =728



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 7 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =819



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 8 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underLIVING.  Active members are: ANIMAL, ORGAN
Simulation iteration (i.e., total RT) =1447



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    BIRDS = 0.879
  Props:
    From P1 to:    P5 = 0.990
  SPs:
    From SP1.1 to:    SP5.1 = 0.993
    From SP1.2 to:    SP5.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    BIRD = 0.970
    From ENZYME to:    B-WINGS = 0.959

From WorkSpace to ToVerify:
  Groups:
    From BIRDS to:    TOVERIFY = 0.879
  Props:
    From P3 to:
    From P5 to:    P1 = 0.990
    From P10 to:
    From P11 to:
    From P12 to:
  SPs:
    From SP5.1 to:    SP1.1 = 0.993
    From SP5.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    BIRD = 0.970
    From B-WINGS to:    ENZYME = 0.959

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 9 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underLIVING.  Active members are: ANIMAL, ORGAN
Simulation iteration (i.e., total RT) =1448



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALS = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNGS = 0.959

From WorkSpace to ToVerify:
  Groups:
    From ANIMALS to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNGS to:    ENZYME = 0.959

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 10 of inductions/diversity/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P3: CAN (BIRD, FLY)
Iteration (RT) = 1483



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    BIRDS = 0.887
  Props:
    From P1 to:    P3 = 0.879
  SPs:
    From SP1.1 to:
    From SP1.2 to:
  Preds:
    From HAS1 to:
    From HAS2 to:
  Objs:
    From BIRD to:
    From ENZYME to:

From WorkSpace to ToVerify:
  Groups:
    From BIRDS to:    TOVERIFY = 0.887
  Props:
    From P3 to:    P1 = 0.879
    From P10 to:
    From P11 to:
    From P12 to:
  SPs:
    From SP3.1 to:
    From SP3.2 to:
  Preds:
    From CAN1 to:
    From CAN2 to:
  Objs:
    From BIRD to:
    From FLY to:

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 1 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underTHING.  Active members are: LIVING, NON-LIVING
Simulation iteration (i.e., total RT) =830



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:
  Props:
  SPs:
  Preds:
  Objs:

From WorkSpace to ToVerify:
  Groups:
    From CARS to:
  Props:
  SPs:
  Preds:
  Objs:

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 2 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underLIVING.  Active members are: ANIMAL, ORGAN
Simulation iteration (i.e., total RT) =1447



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALS = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNGS = 0.959

From WorkSpace to ToVerify:
  Groups:
    From ANIMALS to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNGS to:    ENZYME = 0.959

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 3 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =699



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 4 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underTHING.  Active members are: LIVING, NON-LIVING
Simulation iteration (i.e., total RT) =830



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:
  Props:
  SPs:
  Preds:
  Objs:

From WorkSpace to ToVerify:
  Groups:
    From CARS to:
  Props:
  SPs:
  Preds:
  Objs:

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 5 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =699



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 6 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underLIVING.  Active members are: ANIMAL, ORGAN
Simulation iteration (i.e., total RT) =1447



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    BIRDS = 0.879
  Props:
    From P1 to:    P5 = 0.990
  SPs:
    From SP1.1 to:    SP5.1 = 0.993
    From SP1.2 to:    SP5.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    BIRD = 0.970
    From ENZYME to:    B-WINGS = 0.959

From WorkSpace to ToVerify:
  Groups:
    From BIRDS to:    TOVERIFY = 0.879
  Props:
    From P3 to:
    From P5 to:    P1 = 0.990
    From P10 to:
    From P11 to:
    From P12 to:
  SPs:
    From SP5.1 to:    SP1.1 = 0.993
    From SP5.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    BIRD = 0.970
    From B-WINGS to:    ENZYME = 0.959

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 7 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =821



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 8 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underLIVING.  Active members are: ANIMAL, ORGAN
Simulation iteration (i.e., total RT) =1340



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    BIRDS = 0.879
  Props:
    From P1 to:    P5 = 0.990
  SPs:
    From SP1.1 to:    SP5.1 = 0.993
    From SP1.2 to:    SP5.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    BIRD = 0.970
    From ENZYME to:    B-WINGS = 0.959

From WorkSpace to ToVerify:
  Groups:
    From BIRDS to:    TOVERIFY = 0.879
  Props:
    From P3 to:
    From P5 to:    P1 = 0.990
    From P10 to:
    From P11 to:
    From P12 to:
  SPs:
    From SP5.1 to:    SP1.1 = 0.993
    From SP5.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    BIRD = 0.970
    From B-WINGS to:    ENZYME = 0.959

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 9 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =809



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 10 of inductions/diversity/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underLIVING.  Active members are: ANIMAL, ORGAN
Simulation iteration (i.e., total RT) =1343



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    ANIMALS = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNGS = 0.959

From WorkSpace to ToVerify:
  Groups:
    From ANIMALS to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNGS to:    ENZYME = 0.959

