Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 1 of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underLIVING.  Active members are: ANIMAL, ORGAN
Simulation iteration (i.e., total RT) =491


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P16: HAS (MONKEY, LUNG)
Iteration (RT) = 678

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1142


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P16: HAS (MONKEY, LUNG)
Iteration (RT) = 1174


Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1255



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT3 = 0.879
  Props:
    From P1 to:    P16 = 0.990
  SPs:
    From SP1.1 to:    SP16.1 = 0.993
    From SP1.2 to:    SP16.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    MONKEY = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT3 to:    TOVERIFY = 0.879
  Props:
    From P16 to:    P1 = 0.990
  SPs:
    From SP16.1 to:    SP1.1 = 0.993
    From SP16.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From MONKEY to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 2 of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =487


Contradiction detected underMAMMAL.  Active members are: RODENT, ELEPHANT
Simulation iteration (i.e., total RT) =495


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ANIMAL, ENZYME)
Iteration (RT) = 639

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ANIMAL, ENZYME)
Iteration (RT) = 1174


Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1258


Contradiction detected underMAMMAL.  Active members are: RODENT, ELEPHANT
Simulation iteration (i.e., total RT) =1259



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT1 = 0.879
  Props:
    From P1 to:    P0 = 0.990
  SPs:
    From SP1.1 to:    SP0.1 = 0.993
    From SP1.2 to:    SP0.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    ENZYME = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT1 to:    TOVERIFY = 0.879
  Props:
    From P0 to:    P1 = 0.990
  SPs:
    From SP0.1 to:    SP1.1 = 0.993
    From SP0.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From ENZYME to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 3 of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underTHING.  Active members are: LIVING, NON-LIVING
Simulation iteration (i.e., total RT) =621


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P4: HAS (CAR, WHEELS)
Iteration (RT) = 714

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P4: HAS (CAR, WHEELS)
Iteration (RT) = 1179


Contradiction detected underTHING.  Active members are: LIVING, NON-LIVING
Simulation iteration (i.e., total RT) =1256



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT2 = 0.879
  Props:
    From P1 to:    P4 = 0.990
  SPs:
    From SP1.1 to:    SP4.1 = 0.993
    From SP1.2 to:    SP4.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    CAR = 0.970
    From ENZYME to:    WHEELS = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT2 to:    TOVERIFY = 0.879
  Props:
    From P4 to:    P1 = 0.990
  SPs:
    From SP4.1 to:    SP1.1 = 0.993
    From SP4.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From CAR to:    BIRD = 0.970
    From WHEELS to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 4 of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =513


Contradiction detected underLIVING.  Active members are: ANIMAL, ORGAN
Simulation iteration (i.e., total RT) =610


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P16: HAS (MONKEY, LUNG)
Iteration (RT) = 670

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1147


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P16: HAS (MONKEY, LUNG)
Iteration (RT) = 1179


Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1260



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT3 = 0.879
  Props:
    From P1 to:    P16 = 0.990
  SPs:
    From SP1.1 to:    SP16.1 = 0.993
    From SP1.2 to:    SP16.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    MONKEY = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT3 to:    TOVERIFY = 0.879
  Props:
    From P16 to:    P1 = 0.990
  SPs:
    From SP16.1 to:    SP1.1 = 0.993
    From SP16.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From MONKEY to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 5 of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 650

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 1163


Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1244



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT1 = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT1 to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 6 of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 653

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1147


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 1178



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT1 = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT1 to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 7 of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underLIVING.  Active members are: ANIMAL, ORGAN
Simulation iteration (i.e., total RT) =493


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P16: HAS (MONKEY, LUNG)
Iteration (RT) = 680

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1144


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P16: HAS (MONKEY, LUNG)
Iteration (RT) = 1174


Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1253



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT3 = 0.879
  Props:
    From P1 to:    P16 = 0.990
  SPs:
    From SP1.1 to:    SP16.1 = 0.993
    From SP1.2 to:    SP16.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    MONKEY = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT3 to:    TOVERIFY = 0.879
  Props:
    From P16 to:    P1 = 0.990
  SPs:
    From SP16.1 to:    SP1.1 = 0.993
    From SP16.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From MONKEY to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 8 of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =483


Contradiction detected underMAMMAL.  Active members are: RODENT, ELEPHANT
Simulation iteration (i.e., total RT) =491


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ANIMAL, ENZYME)
Iteration (RT) = 635

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1139


Contradiction detected underMAMMAL.  Active members are: RODENT, ELEPHANT
Simulation iteration (i.e., total RT) =1140


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ANIMAL, ENZYME)
Iteration (RT) = 1166



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT1 = 0.879
  Props:
    From P1 to:    P0 = 0.990
  SPs:
    From SP1.1 to:    SP0.1 = 0.993
    From SP1.2 to:    SP0.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    ENZYME = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT1 to:    TOVERIFY = 0.879
  Props:
    From P0 to:    P1 = 0.990
  SPs:
    From SP0.1 to:    SP1.1 = 0.993
    From SP0.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From ENZYME to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 9 of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =600


Contradiction detected underMAMMAL.  Active members are: RODENT, ELEPHANT
Simulation iteration (i.e., total RT) =608


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ANIMAL, ENZYME)
Iteration (RT) = 639

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ANIMAL, ENZYME)
Iteration (RT) = 1173


Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1257


Contradiction detected underMAMMAL.  Active members are: RODENT, ELEPHANT
Simulation iteration (i.e., total RT) =1258



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT1 = 0.879
  Props:
    From P1 to:    P0 = 0.990
  SPs:
    From SP1.1 to:    SP0.1 = 0.993
    From SP1.2 to:    SP0.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    ENZYME = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT1 to:    TOVERIFY = 0.879
  Props:
    From P0 to:    P1 = 0.990
  SPs:
    From SP0.1 to:    SP1.1 = 0.993
    From SP0.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From ENZYME to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 10 of inductions/diversity2/diverseschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underLIVING.  Active members are: ANIMAL, ORGAN
Simulation iteration (i.e., total RT) =493


Contradiction detected underTHING.  Active members are: LIVING, NON-LIVING
Simulation iteration (i.e., total RT) =494


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P16: HAS (MONKEY, LUNG)
Iteration (RT) = 681

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1144


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P16: HAS (MONKEY, LUNG)
Iteration (RT) = 1174


Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1253



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT3 = 0.879
  Props:
    From P1 to:    P16 = 0.990
  SPs:
    From SP1.1 to:    SP16.1 = 0.993
    From SP1.2 to:    SP16.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    MONKEY = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT3 to:    TOVERIFY = 0.879
  Props:
    From P16 to:    P1 = 0.990
  SPs:
    From SP16.1 to:    SP1.1 = 0.993
    From SP16.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From MONKEY to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 1 of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 654

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1142


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 1173



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT1 = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT1 to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 2 of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =599


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 636

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 1165


Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1251



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT1 = 0.879
  Props:
    From P1 to:    P0 = 0.990
  SPs:
    From SP1.1 to:    SP0.1 = 0.993
    From SP1.2 to:    SP0.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ELEPHANT = 0.970
    From ENZYME to:    ENZYME = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT1 to:    TOVERIFY = 0.879
  Props:
    From P0 to:    P1 = 0.990
  SPs:
    From SP0.1 to:    SP1.1 = 0.993
    From SP0.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ELEPHANT to:    BIRD = 0.970
    From ENZYME to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 3 of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =483


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 634

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 1165


Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1251



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT1 = 0.879
  Props:
    From P1 to:    P0 = 0.990
  SPs:
    From SP1.1 to:    SP0.1 = 0.993
    From SP1.2 to:    SP0.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ELEPHANT = 0.970
    From ENZYME to:    ENZYME = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT1 to:    TOVERIFY = 0.879
  Props:
    From P0 to:    P1 = 0.990
  SPs:
    From SP0.1 to:    SP1.1 = 0.993
    From SP0.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ELEPHANT to:    BIRD = 0.970
    From ENZYME to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 4 of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =508


Contradiction detected underLIVING.  Active members are: ANIMAL, ORGAN
Simulation iteration (i.e., total RT) =605


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P16: HAS (MONKEY, LUNG)
Iteration (RT) = 666

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1140


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P16: HAS (MONKEY, LUNG)
Iteration (RT) = 1170


Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1249



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT3 = 0.879
  Props:
    From P1 to:    P16 = 0.990
  SPs:
    From SP1.1 to:    SP16.1 = 0.993
    From SP1.2 to:    SP16.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    MONKEY = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT3 to:    TOVERIFY = 0.879
  Props:
    From P16 to:    P1 = 0.990
  SPs:
    From SP16.1 to:    SP1.1 = 0.993
    From SP16.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From MONKEY to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 5 of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underTHING.  Active members are: LIVING, NON-LIVING
Simulation iteration (i.e., total RT) =597

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underTHING.  Active members are: LIVING, NON-LIVING
Simulation iteration (i.e., total RT) =1257



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 6 of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underLIVING.  Active members are: ANIMAL, ORGAN
Simulation iteration (i.e., total RT) =491


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 666

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 1168


Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1249



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT1 = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT1 to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 7 of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =489


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 640

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 1172


Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1258



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT1 = 0.879
  Props:
    From P1 to:    P0 = 0.990
  SPs:
    From SP1.1 to:    SP0.1 = 0.993
    From SP1.2 to:    SP0.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ELEPHANT = 0.970
    From ENZYME to:    ENZYME = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT1 to:    TOVERIFY = 0.879
  Props:
    From P0 to:    P1 = 0.990
  SPs:
    From SP0.1 to:    SP1.1 = 0.993
    From SP0.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ELEPHANT to:    BIRD = 0.970
    From ENZYME to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 8 of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underLIVING.  Active members are: ANIMAL, ORGAN
Simulation iteration (i.e., total RT) =484


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 659

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underBIO-PART.  Active members are: ORGAN, ENZYME
Simulation iteration (i.e., total RT) =1134


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P1: HAS (ANIMAL, LUNG)
Iteration (RT) = 1165



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT1 = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ANIMAL = 0.970
    From ENZYME to:    LUNG = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT1 to:    TOVERIFY = 0.879
  Props:
    From P1 to:    P1 = 0.990
  SPs:
    From SP1.1 to:    SP1.1 = 0.993
    From SP1.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ANIMAL to:    BIRD = 0.970
    From LUNG to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 9 of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =601


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 638

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 1173


Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1259



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT1 = 0.879
  Props:
    From P1 to:    P0 = 0.990
  SPs:
    From SP1.1 to:    SP0.1 = 0.993
    From SP1.2 to:    SP0.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ELEPHANT = 0.970
    From ENZYME to:    ENZYME = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT1 to:    TOVERIFY = 0.879
  Props:
    From P0 to:    P1 = 0.990
  SPs:
    From SP0.1 to:    SP1.1 = 0.993
    From SP0.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ELEPHANT to:    BIRD = 0.970
    From ENZYME to:    ENZYME = 0.970

Note: DATA/inductions/diversity/Schema.sym
Note: This SYM file generated by LISA.

* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Batch: 10 runs of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 


* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *


* * * * * * * * * * * * * * * * * * * * * * * * * * * 
Run 10 of inductions/diversity2/similarschema
* * * * * * * * * * * * * * * * * * * * * * * * * * * 

Sequence:
Seq. 0    Driver:ToVerify    Recip :    Fire control:groups    Goals: VERIFY RETRIEVE     Phase set: P1:HAS (BIRD, ENZYME)
Seq. 1    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =488


Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 639

Seq. 2    Driver:ToVerify    Recip : WorkSpace    Fire control:groups-d    Goals: VERIFY MAP     Phase set: P1:HAS (BIRD, ENZYME)

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, ENZYME) matches prop P0: HAS (ELEPHANT, ENZYME)
Iteration (RT) = 1178


Contradiction detected underANIMAL.  Active members are: MAMMAL, BIRD
Simulation iteration (i.e., total RT) =1264



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From ToVerify to WorkSpace:
  Groups:
    From TOVERIFY to:    EFFECT1 = 0.879
  Props:
    From P1 to:    P0 = 0.990
  SPs:
    From SP1.1 to:    SP0.1 = 0.993
    From SP1.2 to:    SP0.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From BIRD to:    ELEPHANT = 0.970
    From ENZYME to:    ENZYME = 0.970

From WorkSpace to ToVerify:
  Groups:
    From EFFECT1 to:    TOVERIFY = 0.879
  Props:
    From P0 to:    P1 = 0.990
  SPs:
    From SP0.1 to:    SP1.1 = 0.993
    From SP0.2 to:    SP1.2 = 0.993
  Preds:
    From HAS1 to:    HAS1 = 0.970
    From HAS2 to:    HAS2 = 0.970
  Objs:
    From ELEPHANT to:    BIRD = 0.970
    From ENZYME to:    ENZYME = 0.970

