Note: /Users/john/Dropbox/Zach's CDL Folder/Lisa and Inherence Heuristic/VersEx2.01/Data/AZ/Schemas/SchemaEx1.sch
Note: This SYM file generated by LISA.

Analog SchemaEx1

  DefObjs
    'FIRSTGUY' HUMAN =1.00 PERSON =1.00 ANIMATE =1.00 ALIVE =1.00 MALE =1.00 BANKER =0.45 DESERVES_DEATH =0.45 1% =0.45 LARRY =0.45 MECHANIC =0.56 FATHER =0.56 DUDE =0.56 ;
    'OJ' ORANGE =1.00 JUICE =1.00 LIQUID =1.00 BREAKFAST =1.00 MORNING =1.00 ;
  end { def objs

  DefPreds
    'DRINK'
     [ INGEST1 =0.50 CONSUME1 =0.50 LIQUID1 =1.00 SWALLOW1 =0.50 ]
     [ INGEST2 =0.50 CONSUME2 =0.50 LIQUID2 =1.00 SWALLOW2 =0.50 ]
     ; { done with 'DRINK'
  end { def preds

  DefProps
    'P0' 'DRINK' ( 'FIRSTGUY' 'OJ' ) 0.000 ;
  end { def props

  DefGroups
    Cause ( ) 0.000 ;
    'Effect-1'
       Groups: ;
       Props: 'P0' ;
       Semantics: EFFECT ;
      %%
  end { def groups
done { analog SchemaEx1
