Run of LISA Version Ex 1.06; last modified 3/05/08

Note: Semantic/test1a.sym
Note: First attempt to fuck with semantic relations and detect contradictions
Note: Has bird wings?  (it ougta not detect a contradiction here)

* * * * * * * * * * * * * * * * * * * * *
Parameters values:
    Neurally-plausible WM
    Semantic Noise = 0.0000
    Semantic Death = 0.0000
    Attention = 1.0000
    Within-group support = 1.0000
    Driver Inhibition = 1.0000
    Recip Inhibition = 1.0000
    Hebb Learning Rate = 1.0000
    Bail Upon Settling = False
    Using Vers142 Mapping Algorithm
* * * * * * * * * * * * * * * * * * * * *

Sequence:
Seq. 0    Driver:ToVerify    Recip : WorldKnowledge    Fire control:props    Goals: NORMAL     Phase set: P1

Truth verified! (I.e., Lack-of-anomaly detected)
The assertion HAS (BIRD, WINGS) matches prop P1: HAS (BIRD, WINGS)
Iteration (RT) = 404



* * * * * * * * * * * * * * * *
* * * Mapping Connections * * *
* * * * * * * * * * * * * * * *

From WorldKnowledge to ToVerify:
  Groups:
  Props:
    From P1 to:
  SPs:
    From SP1.1 to:
    From SP1.2 to:
  Preds:
    From HAS1 to:
    From HAS2 to:
  Objs:
    From BIRD to:
    From WINGS to:

From ToVerify to WorldKnowledge:
  Groups:
  Props:
    From P1 to:
  SPs:
    From SP1.1 to:
    From SP1.2 to:
  Preds:
    From HAS1 to:
    From HAS2 to:
  Objs:
    From BIRD to:
    From WINGS to:

